### ISSUE TITLE
Any possibility to work with ensembles and stacked dimensions?

### ISSUE THREAD

**Issue by matteodefelice** [ajdawson/eofs#100]
I would like to compute an EOF on an ensemble (a xarray with `member` dimension) *not* having different EOFs for all the members. I would like, for example, to stack the dimensions `time` and `member`, and then computing the EOF on that dimension. Is it possible or it would be better to stick to the plain `sklearn` functions?

**Comment by ajdawson** [comment]
As discussed in #98, I don't plan on supporting this directly as a special case. It would be preferable in my opinion to pre-process your input so that it has a single "record" dimension that contains both time and member and then pass this into eofs. You can absolutely achieve what you want if you reshape to combine the time and member dimensions and then use eofs.
