### ISSUE TITLE
xarray projectField function time coords mistake

### ISSUE THREAD

**Issue by lynch123** [ajdawson/eofs#85]
I discovered that (line 639 eofs/xarray):

           pcs.coords.update({coord.name: (coord.dims, coord)
                               for coord in self._time_ndcoords})

should instead use the new data's time coordinates with time_ndcoords:

           pcs.coords.update({coord.name: (coord.dims, coord)
                               for coord in time_ndcoords})

With this modification it is possible find the EOF's of X1 then project the fields from X2 (than contain a different set of time coordinates) back onto the EOF's of X1 using projectField. Your implementation references the X1 time coordinates (by calling self._time_ndcoords).

(First time creating an issue on Github so sorry if it's not formatted etc. the correct way)

**Comment by ajdawson** [comment]
Thanks for taking the time to report, much appreciated. Since it seems you figured out how to fix it, perhaps you would like to have a go at implementing the fix?

You need a fork of this repository (looks like you already have that) then make your changes, push your branch to your fork, and submit a pull request to this repository. If you aren't comfortable doing this then I will eventually get round to implementing the fix (but probably not soon). If you need any help, just ask.
